schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - master
  always: true

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: git checkout master
  displayName: 'Checkout Branch'

- task: UsePythonVersion@0
