schedules:
- cron: "0 0 * * *"
  displayName: Nightly build
  branches:
    include:
    - master
  always: true

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: git checkout master
  displayName: 'Checkout Branch'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' 
    addToPath: true 

- script: pip install pandas pyyaml
  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'starcounter.py'
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStd